# Generated by Django 5.2.8 on 2025-11-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('url_projeto', models.URLField(blank=True, null=True)),
                ('destaque', models.BooleanField(default=False, help_text='Aparecerá no slider da home')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='projetos.categoria')),
            ],
            options={
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
